version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysuperpass
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
    
    ports:
      - "5432:5432"