version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysuperpass
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
    
    ports:
      - "5432:5432"
  
  web:
    build:
      context: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:mysuperpass@database:5432/db
      - NODE_ENV=development
      - PORT=3001
    command: >
      sh -c "
        cd packages/database &&
        npx prisma generate &&
        npx prisma migrate dev --name init --preview-feature &&
        cd /app &&
        pnpm dev
      "
